insert into User values (6,'goyal',sysdate(),'aditya','$2a$10$lEeILILXBEG41X8XUBN/gee86FGTYV3BuATbhjpFDaeqSMK8XHfFC','PUPIL','agoyal',null)
insert into User values (7,'shukla',sysdate(),'susheel','$2a$10$lEeILILXBEG41X8XUBN/gee86FGTYV3BuATbhjpFDaeqSMK8XHfFC','PUPIL','sushukla',null)
insert into Teacher values (1)
insert into Teacher values (2)
insert into Teacher values (3)
insert into User values (8,'Wilson',sysdate(),'Sam','$2a$10$lEeILILXBEG41X8XUBN/gee86FGTYV3BuATbhjpFDaeqSMK8XHfFC','TEACHER','teacher1',1)
insert into User values (9,'White',sysdate(),'Mike','$2a$10$lEeILILXBEG41X8XUBN/gee86FGTYV3BuATbhjpFDaeqSMK8XHfFC','TEACHER','teacher2',2)
insert into User values (10,'Muller',sysdate(),'Angela','$2a$10$lEeILILXBEG41X8XUBN/gee86FGTYV3BuATbhjpFDaeqSMK8XHfFC','TEACHER','teacher3',3)
insert into Pupil values(2,0,null,7)
insert into Pupil values(1,0,null,6)
insert into Course values(1,'Master in Automotive Software Engineering')
insert into Course values(2,'Master in Web Engineering')
insert into Subject values('Formal Specification And Verfication',false,'This is basics Formal Specification for Automive softwares',1,1)
insert into Subject values('Realtime Systems',false,'Introuction to Realtime Time System and scheduling policies',1,1)
insert into Subject values('Automotive Software Engineering',false,'Introduction to principle of Automotive Software Technology',1,2)
insert into Subject values('Data Structure and Algorithms',false,'Introduction to Data Structure and Different Algorithms',2,1)
insert into Subject values('Database Management Systems',false,'Basic Concepts of DBMS',2,1)
insert into Subject values('Neurocomputing',false,'Breif Introduction to Deep Learning and Machine Learning',2,2)
